config:
  validation: true
  warningsAsErrors: false

complexity:
  active: false

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: false

naming:
  active: false

performance:
  active: true

potential-bugs:
  active: true

style:
  active: false
